spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Asdf0823
    url: jdbc:mysql://123:3306/mufengim?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: root

  application:
    name: im-core

# logger 配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000
  servlet:
    context-path: /v1


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
